version: '3'
services:
  rails:
    build: .
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:secret@db:5432/sps_rails_development
  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sps_rails_development
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
